#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
#makeType=${1:-libso}

#wmake $makeType turbulenceModel
wmake libso ./turbulenceModel
wmake libso ./RAS


# ----------------------------------------------------------------- end-of-file
